#! /bin/sh

### BEGIN INIT INFO
# Provides:          httpd-control
# Required-Start:    $local_fs $remote_fs
# Required-Stop:
# X-Start-Before:    rmnologin
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: HTTP control server for STM32
# Description: HTTP control server for STM32
### END INIT INFO

. /lib/lsb/init-functions

set -e
HTTPD=/home/pi/control/httpd.py
case "$1" in
  start)
	if [ -f $HTTPD ]
	then
                nohup python $HTTPD > /var/log/httpd-control.log 2>&1 &
	fi
	;;
  stop|reload|restart|force-reload|status)
	;;
  *)
	echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
